#!/bin/bash -x
#This script allows for dist-upgrade - auto-remove
#Author: Stephen J Kennedy
#version 1.1

THISHOST=$(hostname -f)
DATE=$(date +"%F")
TIME=$(date +"%H:%M:%S")
LOGPATH="/bin/custom"
PID=$BASHPID
LOG="${LOGPATH}/log/${DATE}-${PID}-log"
TEMP="${LOGPATH}/.temp"
MAIL=/usr/bin/mail
TO="medicup@gmail.com"
UPDATE="upgrade dist-upgrade auto-remove" #options for autoUpdate do statement

#mail Function uses mail to distribute results of autoUpdate
mailOutput(){
if [ $? -ne 0 ]
   then
      echo "mail error"
      $MAIL -s "Error with ${HOSTNAME} update: check ${UPDATE}." $TO < $LOG
   else
      echo "Success!"
      $MAIL -s ${DATE}-${THISHOST}  $TO < $LOG
fi
}

#Auto-update and upgrade process. Checks for need to dist-upgrade and
#exits with return 3 if dist-upgrade needed.

autoUpdate (){
echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
sudo apt-get update

for UPDATE in $UPDATE
do
  apt-get --assume-yes $UPDATE >> $LOG ||  return 1
  echo "apt-get ${UPDATE} successful!" >> $LOG
done
}

autoUpdate
mailOutput
exit 0
