#!/bin/bash 
#This script allows for dist-upgrade - auto-remove
#Author: Stephen J Kennedy
#version 1.2
#DEBUG used with -x (reports shell name, line number, and associated function)
PS4='+ $BASH_SOURCE : $LINENO : ${FUNCNAME[0]} ()'

DATE=$(date +"%F")
TIME=$(date +"%H:%M:%S")
LOGPATH="/bin/custom"
PID=$BASHPID
LOG="${LOGPATH}/log/${DATE}-${PID}-log"
TEMP="${LOGPATH}/.temp"
MAIL=/usr/bin/mail
TO="medicup@gmail.com"

#options for autoUpdate do statement
#mail Function uses mail to distribute results of autoUpdate
mailOutput(){
   case $? in
      0)
         echo "Success!"
         $MAIL -s ${DATE}-${HOSTNAME}  $TO < $LOG
         ;;
      1)
         echo "mail error"
         $MAIL -s "Error with ${HOSTNAME} update: check ${UPDATE}." $TO < $LOG
         ;;
      2)
         echo "Reboot needed"
         $MAIL -s "Reboot required for ${HOSTNAME}: shutdown pending." $TO < $LOG
         apt-get autoremove
         shutdown -r now
         ;;
   esac
}

#Auto-update that includes dist-upgrade
autoUpdate (){
   echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
   apt-get update
   for UPDATE in upgrade dist-upgrade
   do
     apt-get $UPDATE --assume-yes >> $LOG || return 1
     if [ -f /var/run/reboot-required ]
        then
            echo "Reboot required" && return 2
     fi
   done
}

autoUpdate
mailOutput
exit 0
